version: '3'

services:
  db:
    image: postgres
    restart: always
    ports: 
      - 3002:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: apa

  adminer:
    image: adminer
    restart: always
    ports:
      - 3003:8080