version: '3'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin12345"
      ACCEPT_EULA: "Y"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080